### ISSUE TITLE
CUDA out of memory.

### ISSUE THREAD

**Issue by whatiskeptiname** [fudan-zvg/4d-gaussian-splatting#16]
While training on the Cook Spinach dataset "CUDA out of memory." the error occurs at about 11K iteration. Is this expected?

GPU: Nvidia A10G.

```
Traceback (most recent call last):
  File "train.py", line 403, in <module>
    args.gaussian_dim, args.time_duration, args.num_pts, args.num_pts_ratio, args.rot_4d, args.force_sh_3d, args.batch_size)
  File "train.py", line 162, in training
    loss.backward()
  File "/home/ec2-user/anaconda3/envs/4d_gaussian_splatting/lib/python3.7/site-packages/torch/_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/ec2-user/anaconda3/envs/4d_gaussian_splatting/lib/python3.7/site-packages/torch/autograd/__init__.py", line 175, in backward
    allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to run the backward pass
  File "/home/ec2-user/anaconda3/envs/4d_gaussian_splatting/lib/python3.7/site-packages/torch/autograd/function.py", line 253, in apply
    return user_fn(self, *args)
  File "/home/ec2-user/redefine/source/4d-gaussian-splatting/gaussian_renderer/diff_gaussian_rasterization.py", line 198, in backward
    grad_rotations, grad_rotations_r) = _C.rasterize_gaussians_backward(*args)
RuntimeError: CUDA out of memory. Tried to allocate 64.00 MiB (GPU 0; 21.99 GiB total capacity; 20.68 GiB already allocated; 33.06 MiB free; 20.97 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by Alexander0Yang** [comment]
Sorry for the late response. 
We have only tested this scene on the NVIDIA RTX A6000 GPU. 
I recommend stopping densification based on the number of points before exceeding GPU memory, which typically does not affect the performance too much. 
Additionally, some works such as [c3dgs](https://github.com/KeKsBoTer/c3dgs) and [Compact-3DGS](https://github.com/maincold2/Compact-3DGS) can be referenced for reducing memory consumption.

**Comment by xiao10ma** [comment]
I have a same problem, have you solved it @whatiskeptiname ?
