### ISSUE TITLE
Issue with libopenh264.so.5 while running n3v2blender.py script

### ISSUE THREAD

**Issue by SHIBOYA** [fudan-zvg/4d-gaussian-splatting#43]
Dear Zeyu,

I am currently working with the 4D Gaussian Splatting project and encountered an issue while attempting to run the `n3v2blender.py` script. When I execute the script with the following command:

```bash
python scripts/n3v2blender.py /root/autodl-tmp/N3V/cut_roasted_beef
```

I receive the following error message:

```bash
==== running: ffmpeg -i /root/autodl-tmp/N3V/cut_roasted_beef/cam20.mp4 -start_number 0 /root/autodl-tmp/N3V/cut_roasted_beef/images//cam20_%04d.png
ffmpeg: error while loading shared libraries: libopenh264.so.5: cannot open shared object file: No such file or directory
FATAL: command failed
```

I have tried several solutions, including installing the `openh264` library and adding the `libde265` repository, but the issue persists. Here are the steps I followed:

1. Tried to install `openh264` directly using `sudo apt-get install openh264`, but it was not found.
2. Added the `libde265` repository and installed it manually:
   - Added the repository using `sudo add-apt-repository ppa:strukturag/libde265`
   - Installed `openh264` using `sudo apt-get install openh264`
3. Downloaded and manually installed the OpenH264 library from GitHub:
   - Downloaded the library using `wget`
   - Extracted and moved the library to `/usr/lib`
   - Updated the linker cache using `sudo ldconfig`

Despite these efforts, I still encounter the same error. Could you please provide guidance on how to resolve this issue or any additional steps I might be missing?

Thank you very much for your time and assistance.

Best regards!

**Comment by Yujie-G** [comment]
This works for me: [](https://stackoverflow.com/questions/62213783/ffmpeg-error-while-loading-shared-libraries-libopenh264-so-5) ; try also `which ffmpeg` to find the path and then deactivate if it's in `/usr/lib/` dir

**Comment by SHIBOYA** [comment]
After install ffmpeg, I encountered an error while running train.py. The error message indicates "Could not recognize scene type!".
```
@ubun:~/4d-gaussian-splatting$ CUDA_VISIBLE_DEVICES=0 python train.py --config /data/shiboya/4d-gaussian-splatting/configs/dnerf/jumpingjacks.yaml
Using /data/shiboya/.cache/torch_extensions/py37_cu116 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /data/shiboya/.cache/torch_extensions/py37_cu116/diff_gaussian_rasterization/build.ninja...
Building extension module diff_gaussian_rasterization...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module diff_gaussian_rasterization...
Optimizing output/dnerf/jumpingjacks
Output folder: output/dnerf/jumpingjacks [30/07 17:39:07]
Tensorboard not available: not logging progress [30/07 17:39:07]
Traceback (most recent call last):
  File "train.py", line 403, in <module>
    args.gaussian_dim, args.time_duration, args.num_pts, args.num_pts_ratio, args.rot_4d, args.force_sh_3d, args.batch_size)
  File "train.py", line 46, in training
    scene = Scene(dataset, gaussians, num_pts=num_pts, num_pts_ratio=num_pts_ratio, time_duration=time_duration)
  File "/data/shiboya/4d-gaussian-splatting/scene/__init__.py", line 52, in __init__
    assert False, "Could not recognize scene type!"
AssertionError: Could not recognize scene type!
```

**Comment by guoshoucheng** [comment]
> After install ffmpeg, I encountered an error while running train.py. The error message indicates "Could not recognize scene type!".
> 
> ```
> @ubun:~/4d-gaussian-splatting$ CUDA_VISIBLE_DEVICES=0 python train.py --config /data/shiboya/4d-gaussian-splatting/configs/dnerf/jumpingjacks.yaml
> Using /data/shiboya/.cache/torch_extensions/py37_cu116 as PyTorch extensions root...
> Detected CUDA files, patching ldflags
> Emitting ninja build file /data/shiboya/.cache/torch_extensions/py37_cu116/diff_gaussian_rasterization/build.ninja...
> Building extension module diff_gaussian_rasterization...
> Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
> ninja: no work to do.
> Loading extension module diff_gaussian_rasterization...
> Optimizing output/dnerf/jumpingjacks
> Output folder: output/dnerf/jumpingjacks [30/07 17:39:07]
> Tensorboard not available: not logging progress [30/07 17:39:07]
> Traceback (most recent call last):
>   File "train.py", line 403, in <module>
>     args.gaussian_dim, args.time_duration, args.num_pts, args.num_pts_ratio, args.rot_4d, args.force_sh_3d, args.batch_size)
>   File "train.py", line 46, in training
>     scene = Scene(dataset, gaussians, num_pts=num_pts, num_pts_ratio=num_pts_ratio, time_duration=time_duration)
>   File "/data/shiboya/4d-gaussian-splatting/scene/__init__.py", line 52, in __init__
>     assert False, "Could not recognize scene type!"
> AssertionError: Could not recognize scene type!
> ```

thefile "configs/dynerf/cook_spinach.yaml"   datapath error
